print("Give me a word!")
this = input()
print("Give me a second word!")
that = input()
print("\nGreat, now your favorite number?")
thi = input()
print("And your second-favorite number...")
tha = input()
print("\nWhew!  Wasn't that fun?")